## 2026년 부산 초등학교 학년별·학급별 학생 수 불러오기

CSV 파일을 판다스 데이터프레임으로 읽습니다.

In [1]:
import pandas as pd

In [2]:
csv_path = '2026년도_학년별·학급별 학생수(초)_부산광역시교육청.csv'
df_students = pd.read_csv(csv_path, encoding='utf-8-sig')

df_students.head()

,시도교육청,교육지원청,지역,정보공시 학교코드,학교명,학교급코드,설립구분,제외여부,제외사유,1학년 학급수,...,특수학급 학생수,특수학급 학급당 학생수,순회학급 학급수,순회학급 학생수,순회학급 학급당 학생수,학급수(계),학생수(계),학급당 학생수(계),교사수,수업교원 1인당 학생수
0,부산광역시교육청,부산광역시동래교육지원청,부산광역시 연제구,S000003559,부산교육대학교부설초등학교,2,국립,N,NaN,4,...,5,5.0,0,0,0,25,528,21.1,29,18.2
1,부산광역시교육청,부산광역시서부교육지원청,부산광역시 중구,S020000625,광일초등학교,2,공립,N,NaN,1,...,5,5.0,0,0,0,11,170,15.5,14,12.1
2,부산광역시교육청,부산광역시서부교육지원청,부산광역시 중구,S020000626,남성초등학교,2,사립,N,NaN,3,...,0,0.0,0,0,0,18,429,23.8,23,18.7
3,부산광역시교육청,부산광역시남부교육지원청,부산광역시 남구,S020000628,대남초등학교,2,공립,N,NaN,2,...,5,5.0,0,0,0,16,278,17.4,18,15.4
4,부산광역시교육청,부산광역시남부교육지원청,부산광역시 남구,S020000629,대연초등학교,2,공립,N,NaN,3,...,10,5.0,0,0,0,33,703,21.3,39,18.0

In [3]:
columns_to_keep = [
    "시도교육청",
    "지역",
    "정보공시 학교코드",
    "학교명",
    "설립구분",
    "제외여부",
    "1학년 학생수",
    "2학년 학생수",
    "3학년 학생수",
    "4학년 학생수",
    "5학년 학생수",
    "6학년 학생수",
    "특수학급 학생수",
    "순회학급 학생수",
    "학급수(계)",
    "학생수(계)",
    "교사수",
]

df_students = df_students[columns_to_keep]

In [4]:
df_students.info()

<class 'pandas.DataFrame'>
RangeIndex: 302 entries, 0 to 301
Data columns (total 17 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   시도교육청      302 non-null    str
 1   지역         302 non-null    str
 2   정보공시 학교코드  302 non-null    str
 3   학교명        302 non-null    str
 4   설립구분       302 non-null    str
 5   제외여부       302 non-null    str
 6   1학년 학생수    302 non-null    int64
 7   2학년 학생수    302 non-null    int64
 8   3학년 학생수    302 non-null    int64
 9   4학년 학생수    302 non-null    int64
 10  5학년 학생수    302 non-null    int64
 11  6학년 학생수    302 non-null    int64
 12  특수학급 학생수   302 non-null    int64
 13  순회학급 학생수   302 non-null    int64
 14  학급수(계)     302 non-null    int64
 15  학생수(계)     302 non-null    int64
 16  교사수        302 non-null    int64
dtypes: int64(11), str(6)
memory usage: 40.2 KB

In [5]:
df_students

,시도교육청,지역,정보공시 학교코드,학교명,설립구분,제외여부,1학년 학생수,2학년 학생수,3학년 학생수,4학년 학생수,5학년 학생수,6학년 학생수,특수학급 학생수,순회학급 학생수,학급수(계),학생수(계),교사수
0,부산광역시교육청,부산광역시 연제구,S000003559,부산교육대학교부설초등학교,국립,N,79,79,79,95,96,95,5,0,25,528,29
1,부산광역시교육청,부산광역시 중구,S020000625,광일초등학교,공립,N,19,16,23,40,33,34,5,0,11,170,14
2,부산광역시교육청,부산광역시 중구,S020000626,남성초등학교,사립,N,90,90,72,58,60,59,0,0,18,429,23
3,부산광역시교육청,부산광역시 남구,S020000628,대남초등학교,공립,N,29,45,59,35,63,42,5,0,16,278,18
4,부산광역시교육청,부산광역시 남구,S020000629,대연초등학교,공립,N,72,86,106,125,141,163,10,0,33,703,39
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
297,부산광역시교육청,부산광역시 기장군,S020002277,일광초등학교,공립,N,141,145,187,194,181,176,11,0,44,1035,55
298,부산광역시교육청,부산광역시 기장군,S020002312,해빛초등학교,공립,N,186,179,163,203,191,178,12,0,46,1112,54
299,부산광역시교육청,부산광역시 강서구,S020002353,대저중앙초등학교,공립,N,250,226,201,191,184,147,6,0,48,1205,55
300,부산광역시교육청,부산광역시 강서구,S020002361,명문초등학교,공립,N,173,199,225,219,193,156,9,0,51,1174,59
301,부산광역시교육청,부산광역시 강서구,S020002370,강서초등학교,공립,N,111,74,93,59,58,44,7,0,27,446,32

In [6]:
df_locations = pd.read_csv(
    "전국초중등학교위치표준데이터.csv",
    encoding="utf-8-sig"
)

df_locations.info()

<class 'pandas.DataFrame'>
RangeIndex: 12011 entries, 0 to 12010
Data columns (total 20 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   학교ID      12011 non-null  str
 1   학교명       12011 non-null  str
 2   학교급구분     12011 non-null  str
 3   설립일자      12011 non-null  str
 4   설립형태      12011 non-null  str
 5   본교분교구분    12011 non-null  str
 6   운영상태      12011 non-null  str
 7   소재지지번주소   12011 non-null  str
 8   소재지도로명주소  11999 non-null  str
 9   시도교육청코드   12011 non-null  int64
 10  시도교육청명    12011 non-null  str
 11  교육지원청코드   12011 non-null  int64
 12  교육지원청명    12011 non-null  str
 13  생성일자      12011 non-null  str
 14  변경일자      12004 non-null  str
 15  위도        12011 non-null  float64
 16  경도        12011 non-null  float64
 17  데이터기준일자   12011 non-null  str
 18  제공기관코드    12011 non-null  str
 19  제공기관명     12011 non-null  str
dtypes: float64(2), int64(2), str(16)
memory usage: 1.8 MB

In [7]:
df_busan_elementary = df_locations[
    (df_locations["소재지지번주소"].str.contains("부산", na=False))
    & (df_locations["학교급구분"] == "초등학교")
].copy()

In [8]:
df_busan_elementary.info()

<class 'pandas.DataFrame'>
Index: 305 entries, 10 to 11975
Data columns (total 20 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   학교ID      305 non-null    str
 1   학교명       305 non-null    str
 2   학교급구분     305 non-null    str
 3   설립일자      305 non-null    str
 4   설립형태      305 non-null    str
 5   본교분교구분    305 non-null    str
 6   운영상태      305 non-null    str
 7   소재지지번주소   305 non-null    str
 8   소재지도로명주소  305 non-null    str
 9   시도교육청코드   305 non-null    int64
 10  시도교육청명    305 non-null    str
 11  교육지원청코드   305 non-null    int64
 12  교육지원청명    305 non-null    str
 13  생성일자      305 non-null    str
 14  변경일자      305 non-null    str
 15  위도        305 non-null    float64
 16  경도        305 non-null    float64
 17  데이터기준일자   305 non-null    str
 18  제공기관코드    305 non-null    str
 19  제공기관명     305 non-null    str
dtypes: float64(2), int64(2), str(16)
memory usage: 50.0 KB

In [9]:
df_merged = pd.merge(
    df_students,
    df_busan_elementary,
    on="학교명",
    how="inner"
)

df_merged.head()

,시도교육청,지역,정보공시 학교코드,학교명,설립구분,제외여부,1학년 학생수,2학년 학생수,3학년 학생수,4학년 학생수,...,시도교육청명,교육지원청코드,교육지원청명,생성일자,변경일자,위도,경도,데이터기준일자,제공기관코드,제공기관명
0,부산광역시교육청,부산광역시 연제구,S000003559,부산교육대학교부설초등학교,국립,N,79,79,79,95,...,부산광역시교육청,7191000,부산광역시동래교육지원청,2013-11-29,2025-10-25,35.195693,129.077082,2026-03-20,B554398,한국교육시설안전원
1,부산광역시교육청,부산광역시 중구,S020000625,광일초등학교,공립,N,19,16,23,40,...,부산광역시교육청,7171000,부산광역시서부교육지원청,2013-11-29,2025-10-25,35.104004,129.029845,2026-03-20,B554398,한국교육시설안전원
2,부산광역시교육청,부산광역시 중구,S020000626,남성초등학교,사립,N,90,90,72,58,...,부산광역시교육청,7171000,부산광역시서부교육지원청,2013-11-29,2025-10-25,35.105736,129.034552,2026-03-20,B554398,한국교육시설안전원
3,부산광역시교육청,부산광역시 남구,S020000628,대남초등학교,공립,N,29,45,59,35,...,부산광역시교육청,7181000,부산광역시남부교육지원청,2013-11-29,2025-10-25,35.148856,129.097235,2026-03-20,B554398,한국교육시설안전원
4,부산광역시교육청,부산광역시 남구,S020000629,대연초등학교,공립,N,72,86,106,125,...,부산광역시교육청,7181000,부산광역시남부교육지원청,2013-11-29,2025-10-25,35.137237,129.092286,2026-03-20,B554398,한국교육시설안전원

In [10]:
df_merged.info()

<class 'pandas.DataFrame'>
RangeIndex: 303 entries, 0 to 302
Data columns (total 36 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   시도교육청      303 non-null    str
 1   지역         303 non-null    str
 2   정보공시 학교코드  303 non-null    str
 3   학교명        303 non-null    str
 4   설립구분       303 non-null    str
 5   제외여부       303 non-null    str
 6   1학년 학생수    303 non-null    int64
 7   2학년 학생수    303 non-null    int64
 8   3학년 학생수    303 non-null    int64
 9   4학년 학생수    303 non-null    int64
 10  5학년 학생수    303 non-null    int64
 11  6학년 학생수    303 non-null    int64
 12  특수학급 학생수   303 non-null    int64
 13  순회학급 학생수   303 non-null    int64
 14  학급수(계)     303 non-null    int64
 15  학생수(계)     303 non-null    int64
 16  교사수        303 non-null    int64
 17  학교ID       303 non-null    str
 18  학교급구분      303 non-null    str
 19  설립일자       303 non-null    str
 20  설립형태       303 non-null    str
 21  본교분교구분     303 non-null    str
 22  운영상태       303 non-null    str
 23  소재지지번주소    303 non-null    str
 24  소재지도로명주소   303 non-null    str
 25  시도교육청코드    303 non-null    int64
 26  시도교육청명     303 non-null    str
 27  교육지원청코드    303 non-null    int64
 28  교육지원청명     303 non-null    str
 29  생성일자       303 non-null    str
 30  변경일자       303 non-null    str
 31  위도         303 non-null    float64
 32  경도         303 non-null    float64
 33  데이터기준일자    303 non-null    str
 34  제공기관코드     303 non-null    str
 35  제공기관명      303 non-null    str
dtypes: float64(2), int64(13), str(21)
memory usage: 85.3 KB

In [11]:
# 각 데이터프레임에서 중복된 학교명 확인
print("students 중복:", df_students["학교명"].duplicated().sum())
print("locations 중복:", df_busan_elementary["학교명"].duplicated().sum())

print(df_students[df_students["학교명"].duplicated(keep=False)]["학교명"])
print(df_busan_elementary[
    df_busan_elementary["학교명"].duplicated(keep=False)
]["학교명"])

students 중복: 1
locations 중복: 1
225    송정초등학교
292    송정초등학교
Name: 학교명, dtype: str
8301    송정초등학교
9362    송정초등학교
Name: 학교명, dtype: str

In [12]:
import folium
import json

from folium import Marker
from folium.plugins import MarkerCluster

In [13]:
# 좌표가 없는 행은 제외하고 지도에 표시
schools = df_merged.dropna(subset=["위도", "경도"]).copy()

# 좌표를 숫자로 변환
schools["위도"] = pd.to_numeric(schools["위도"], errors="coerce")
schools["경도"] = pd.to_numeric(schools["경도"], errors="coerce")
schools = schools.dropna(subset=["위도", "경도"])

# 부산 중심 좌표로 지도 생성
school_map = folium.Map(location=[35.1796, 129.0756], zoom_start=11)

# 학교별 마커 추가
for _, row in schools.iterrows():
    folium.Marker(
        location=[row["위도"], row["경도"]],
        tooltip=row["학교명"],
        popup=f'{row["학교명"]}<br>학생 수: {row["학생수(계)"]}명'
    ).add_to(school_map)

school_map

In [14]:
# 좌표를 숫자로 바꾸고 유효한 좌표만 남기기
schools = df_merged.copy()
schools["위도"] = pd.to_numeric(schools["위도"], errors="coerce")
schools["경도"] = pd.to_numeric(schools["경도"], errors="coerce")
schools = schools.dropna(subset=["위도", "경도"])

print(f"지도에 표시할 학교 수: {len(schools)}")

# 타일 제공자를 CartoDB로 지정
school_map = folium.Map(
    location=[35.1796, 129.0756],
    zoom_start=11,
    tiles="OpenStreetMap"
)

for _, row in schools.iterrows():
    folium.Marker(
        location=[row["위도"], row["경도"]],
        popup=f'{row["학교명"]}<br>학생 수: {row["학생수(계)"]}명'
    ).add_to(school_map)

school_map

지도에 표시할 학교 수: 303

In [15]:
# 좌표를 숫자로 바꾸고 유효한 좌표만 남기기
schools = df_merged.copy()
schools["위도"] = pd.to_numeric(schools["위도"], errors="coerce")
schools["경도"] = pd.to_numeric(schools["경도"], errors="coerce")
schools = schools.dropna(subset=["위도", "경도"])

print(f"지도에 표시할 학교 수: {len(schools)}")

# 타일 제공자를 CartoDB로 지정
school_new_map = folium.Map(
    location=[35.1796, 129.0756],
    zoom_start=11,
    tiles="OpenStreetMap"
)

school_new_map

지도에 표시할 학교 수: 303

In [16]:
geo_str = json.load(open('./busan_gu.json', encoding='utf-8'))

folium.GeoJson(geo_str, name='json_data').add_to(school_new_map)
school_new_map

In [17]:
sch_cluster = MarkerCluster().add_to(school_new_map)

for _, i in df_merged.iterrows():
    # 학생수가 적은 학교는 표시 안하도록 변경할 꺼임
    # print(i['위도'], i['경도']) ## 총학생수, 학교명, 설립구분, 소재지도로명주소
    Marker(location= [i['위도'], i['경도']],
           popup=f"{i['학교명']} / {i['학생수(계)']}명",
           icon=folium.Icon(color='blue')).add_to(sch_cluster)


school_new_map

In [18]:
sch_cluster = MarkerCluster().add_to(school_new_map)

for _, i in df_merged.iterrows():
    marker_color = "red" if i["학생수(계)"] >= 500 else "blue"

    Marker(
        location=[i["위도"], i["경도"]],
        popup=f'{i["학교명"]} / {i["학생수(계)"]}명',
        icon=folium.Icon(color=marker_color)
    ).add_to(sch_cluster)

school_new_map

In [19]:
sch_cluster = MarkerCluster().add_to(school_new_map)

for _, i in df_merged.iterrows():
    marker_color = "red" if i["학생수(계)"] >= 500 else "blue"

    Marker(
        location=[i["위도"], i["경도"]],
        popup=f'{i["학교명"]} / {i["학생수(계)"]}명',
        icon=folium.Icon(color=marker_color)
    ).add_to(sch_cluster)

school_new_map

In [20]:
from branca.element import CssLink

school_map.get_root().header.add_child(
    CssLink(
        "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"
    )
)

In [23]:
for _, row in schools.iterrows():
    marker_color = "red" if row["학생수(계)"] > 900 else "blue"

    folium.Marker(
        location=[row["위도"], row["경도"]],
        popup=f'{row["학교명"]}<br>학생 수: {row["학생수(계)"]}명',
        icon=folium.Icon(
            color=marker_color,
            icon="graduation-cap",
            prefix="fa"
        )
    ).add_to(school_map)

school_map